### ISSUE TITLE
Report for all conversations

### ISSUE THREAD

**Issue by timotoots** [richinfante/iphonebackuptools#10]
At the moment it's implemented to be interactive reading conversations of specific id. We would need a dump for all.

We have implemented alpha version for just the dump. Should me merge or you plan to implement it yourself?

https://github.com/richinfante/iphonebackuptools/commit/663ce04ea7dddaeab61d8e31129a5ec0be5eac3d

**Comment by richinfante** [comment]
I'd say it's a candidate for a merge once it's stable.

**Comment by richinfante** [comment]
Added in #19
