### ISSUE TITLE
Support for older Manifest.mbdb

### ISSUE THREAD

**Issue by timotoots** [richinfante/iphonebackuptools#11]
It seems older iOS uses another format for manifest database.

Do you plan to have support for this one?

**Comment by richinfante** [comment]
I have plans to support this eventually, It'd just require much extra time that I don't currently have at the moment.

**Comment by timotoots** [comment]
Ok, lets see maybe we could do it as well.

**Comment by aguerere** [comment]
This was solved by https://github.com/richinfante/iphonebackuptools/pull/20
