### ISSUE TITLE
Report for Instagram users

### ISSUE THREAD

**Issue by timotoots** [richinfante/iphonebackuptools#12]
There is a cache of Instagram at /Documents/recent-users.coded.

I guess it's not top priority for you, so we could implement report for instagram_users.

**Comment by richinfante** [comment]
Hmm, I haven't given much thought to other apps yet. It may be something for the future but I'm going to need to give some thought to scope and what should be included in the main project.

**Comment by timotoots** [comment]
You could have another repo for user created reports. So they don't mix to much, but collaborative work could still happen. Kind of a plugin system.

**Comment by richinfante** [comment]
That's a good idea, a plugin system may be the best approach

**Comment by richinfante** [comment]
for #41
