### ISSUE TITLE
Report for browser cookies

### ISSUE THREAD

**Issue by timotoots** [richinfante/iphonebackuptools#13]
There are cookies at  /Library/Cookies/Cookies.binarycookies.

We could parse them with this library:

https://www.npmjs.com/package/binary-cookies

We could implement it as it's not so core feature.

**Comment by richinfante** [comment]
I think this functionality may actually be nice to have, I'd be happy to merge a PR for a report type involving this.

**Comment by timotoots** [comment]
Okay, will do.

**Comment by richinfante** [comment]
Added in #19
