### ISSUE TITLE
Report for calls statistics

### ISSUE THREAD

**Issue by timotoots** [richinfante/iphonebackuptools#14]
There is info about all calls made.

report name: calls_statistics

alpha version here, includes support for calls list for older iOS: 

https://github.com/timotoots/iphonebackuptools/commit/57e1da7b7b88bf4bfae1cafdd88e1eded294276a

**Comment by richinfante** [comment]
That sounds like a good report to include. From my testing, It only supports earlier iOS Versions. The newer ones (approx 9.0+) utilize the `Calls2` database for which the report would work like this: `SELECT * from ZCALLDBPROPERTIES`. I can implement the newer iOS Support if need be.

**Comment by timotoots** [comment]
Is the output as key/value pairs okay?

I don't know how easy it is to get to know every iOS version and the formatting. Have you thought of auto-discovery of the databases? For some it would be easy. If calls exists then it's newer function, if not then older function. Might be faster to get on track than mapping the exact history of iOS versions. Just a thought..

**Comment by richinfante** [comment]
That's a good point and I'll explore this for the future. When I was doing my initial research on this, sometimes iOS would leave databases either completely empty or leave them just with empty tables, instead of deleting them altogether.

**Comment by richinfante** [comment]
Added in #19
