### ISSUE TITLE
Idea: configure databases with human readable filenames

### ISSUE THREAD

**Issue by timotoots** [richinfante/iphonebackuptools#15]
Configuring databases with hashes is not so easy to read. Maybe it's better to specify the databases with filenames? As we know them from the manifest.

When I do reverse engineering myself I rename them all and then use the filenames.

Example: 
ade0340f576ee14793c607073bd7e8e409af07a8 => /SystemConfiguration/com.apple.wifi.plist

**Comment by richinfante** [comment]
This would definitely be a nice thing to have. the full backup export functionality that was implemented in (#2) relies on a similar procedure. The only gotcha is that currently early-iOS manifest support is not implemented yet (#11), so for those versions the lookups would currently fail.

**Comment by richinfante** [comment]
Implemented a feature similar to this in #18
