### ISSUE TITLE
Report call history

### ISSUE THREAD

**Issue by timotoots** [richinfante/iphonebackuptools#32]
Some enhancements would be nice:

The "calls" report could return human readable "type" of the call. At the moment it's defined by numbers. It would be better if we decode it to "missed", "blocked" etc.

Also I get "RecentsNumberLocationNotFound" on some locations. Might be good idea to make it an empty string.

We could round the duration to two points of decimal for easier reading.

**Comment by richinfante** [comment]
I'll look into this, decoding the call type seems like an important thing to have from a clarity standpoint.
