### ISSUE TITLE
photos recovery from backup

### ISSUE THREAD

**Issue by MayuraVerma** [richinfante/iphonebackuptools#46]
I have 14.65GB in backup. iTunes is not recognizing the backup.
I need to recover the photos from the backup.

Any help will be greatly appreciated.

**Comment by richinfante** [comment]
Apologies for the delayed reply - you should be able to extract the entire (available) backup contents as long as the backup is not encrypted and damaged beyond repair, by running the following after installing `ibackuptool`:

```bash
# 1. List all backups on the sytem
# Copy the UDID for the target backup
ibackuptool -l

# 2. Extract the files to the folder "ExtractedBackup" on in your Desktop folder
# Replace $UDID with the id from step 1
ibackuptool -b $UDID -r backup.files --extract ~/Desktop/Photos --filter DCIM
```
Hope this helps
