### ISSUE TITLE
Expand Filters to allow regexes

### ISSUE THREAD

**Issue by mediter** [richinfante/iphonebackuptools#49]
does the optional '--filter' only take strings as is, or does it support regular expression?

Right now, I am using ibackuptool to extract one file in particular from iOS backup:
######_mihome.sqlite

This is created by Mi Home app, it contains the tokens for all the IoT devices setup in Mi Home. The tokens would then be used for configure Homebridge.

In each backup, the 'mihome.sqlite' part of the filename is constant, only the first 6 chars are different.

**Comment by richinfante** [comment]
It's currently a simple `CONTAINS` filter (implemented using javascript's `Array.indexOf`) - it will match records that contain the string.

for your case:`--filter "mihome.sqlite"` should probably work for you

I may extend this at some point to allow for regex filters, just hadn't occurred to me when writing this to implement them

**Comment by mediter** [comment]
thank you for the explanation!
