### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by timotoots** [richinfante/iphonebackuptools#5]
We are planning to use this software as part of an art project. As we have many upgrades in mind, it would make sense to add the functionality to this repo as well. Would you be interested in managing the code? Then you could also lead it in a way that makes sense to the original idea. For example how to name command line flags etc.

**Comment by richinfante** [comment]
Hi, That sounds interesting! I'm able to maintain the current codebase and I'll review and merge pull requests for relevant functionality to it's reporting / extractor libraries. If there's any use-case specific features for your project that don't pertain to the general forensics/data extraction use cases, it might be best for those specific features to be placed inside of a dedicated fork.

I'm planning to update the project's wiki in the next few days with much more comprehensive documentation regarding the project's vision, roadmap, code conventions, etc., as well as how it's currently structured and features that are currently in the works (for example, #2), and test suite.

**Comment by timotoots** [comment]
Would be up for a chat to discuss the plans? You might give me feedback if our directions align.

**Comment by timotoots** [comment]
Looks like a great progress!

I might post some feature requests to see what you think about them.
