### ISSUE TITLE
Trying install on brand new up to date OSX system

### ISSUE THREAD

**Issue by darinhouston** [richinfante/iphonebackuptools#52]
It seems to require a later version of sqlite3 and node than is available.  

[darin@server ~ ] sudo npm i -g ibackuptool
Password:
/usr/local/bin/ibackuptool -> /usr/local/lib/node_modules/ibackuptool/tools/cli.js

> sqlite3@4.1.0 install /usr/local/lib/node_modules/ibackuptool/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.1.0 and node@12.11.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ibackuptool/node_modules/sqlite3/lib/binding' 
gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/Users/darin/Library/Caches/node-gyp/12.11.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/ibackuptool/node_modules/sqlite3/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ibackuptool/node_modules/sqlite3/.node-gyp'
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/ibackuptool/node_modules/sqlite3/lib/binding/node-v72-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/local/lib/node_modules/ibackuptool/node_modules/sqlite3/lib/binding/node-v72-darwin-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /usr/local/lib/node_modules/ibackuptool/node_modules/sqlite3
gyp ERR! node -v v12.11.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/ibackuptool/node_modules/sqlite3/lib/binding/node-v72-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/local/lib/node_modules/ibackuptool/node_modules/sqlite3/lib/binding/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/ibackuptool/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/ibackuptool/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/ibackuptool/node_modules/sqlite3
node-pre-gyp ERR! node -v v12.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/ibackuptool/node_modules/sqlite3/lib/binding/node-v72-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/local/lib/node_modules/ibackuptool/node_modules/sqlite3/lib/binding/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/darin/.npm/_logs/2019-10-05T15_22_33_444Z-debug.log
[darin@server ~ ] sqlite3 -v
sqlite3: Error: unknown option: -v
Use -help for a list of options.
[darin@server ~ ] sqlite3 -ver
sqlite3: Error: unknown option: -ver
Use -help for a list of options.
[darin@server ~ ] sqlite3 -version
3.24.0 2018-06-04 14:10:15 95fbac39baaab1c3a84fdfc82ccb7f42398b2e92f18a2a57bce1d4a713cbaapl

**Comment by richinfante** [comment]
the sqlite3 version referred to (4.1.0) is the nodejs module version, not the system's installed sqlite version (which should work fine)

It looks like you're trying to install globally, but don't have permission to write to the directories required. You might want to try to install as your own user, and add it to you $PATH like described in this guide: https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

**Comment by darinhouston** [comment]
I’ll try that. But I’m doing it as root. Why would I not have rights to install globally?

**Comment by richinfante** [comment]
Hmm, I think npm lowers it's privileges now to avoid the security implications of installing as root (all package scripts run as root) - If you you're fine with that, try using:
`npm install --unsafe-perms -g ibackuptool`

see also: https://geedew.com/What-does-unsafe-perm-in-npm-actually-do/

**Comment by richinfante** [comment]
Not to bump an old thread - but it looks like this was actually caused by OSX's new disk permissions via terminal. Docs on how to allow this can be found here: https://github.com/richinfante/iphonebackuptools#terminal-permissions
