### ISSUE TITLE
Report for address book

### ISSUE THREAD

**Issue by timotoots** [richinfante/iphonebackuptools#7]
Name: address_book

Query example: https://gist.github.com/laacz/1180765

Do you plan implementing it yourself or we could help?

**Comment by richinfante** [comment]
I don't plan on implementing it myself (at least in the near future), but this is a feature that would be nice to have in the core, I'd be happy to merge a PR that includes a report for this.

**Comment by timotoots** [comment]
Ok, will do.

**Comment by richinfante** [comment]
Added in #19
