### ISSUE TITLE
Combined reports

### ISSUE THREAD

**Issue by timotoots** [richinfante/iphonebackuptools#8]
We would need a report that combines all reports together in one big export to be used in another software for further analysis. It would make sense to add possibility to include and exclude some reports if needed. 

We have an alpha version here:

https://github.com/richinfante/iphonebackuptools/commit/dc101b12959e75ce20fcdb832b6105f581aadf51

Should we do pull request for this version or you implement it yourself?

**Comment by richinfante** [comment]
Hmm, I didn't think of this! This might be best implemented inside of #6, where each report could be either printed to stdout, or possibly written to disk in a separate file. The format of the individual reports could be dictated by the user selected output formatter. I'll explore implementing this in that PR.

**Comment by timotoots** [comment]
I would be using it with stdout, but why not add the files. My idea was that all the reports form one json object. The report names could be used as keys. Then you could push it further to other software as one data bundle. To stdout or file.

**Comment by richinfante** [comment]
That sounds like a good idea, I'll explore it.
