### ISSUE TITLE
Format MAC address in Wifi report

### ISSUE THREAD

**Issue by timotoots** [richinfante/iphonebackuptools#9]
We need to use the mac address, but the format is not great. Change formatting like this:

el.BSSID.split(':').map((hex) => zpad(hex)).join(':') + '',

We have a feature here, but it changed places a few times. Maybe it's better to add straight to your code.

https://github.com/timotoots/iphonebackuptools/commit/a0bdc46d080f1465d555dff8d7e9224f5dd2b783

**Comment by richinfante** [comment]
That's a good idea, It may make sense to place this as a in a separate module in he `util` directory, and `require()` it as needed to avoid duplicating functionality as it may be needed elsewhere in the future.

**Comment by timotoots** [comment]
Ok, will do.

**Comment by richinfante** [comment]
Implemented in #17
